//Generated by dasze18
package math_expression;

import java.util.*;

public class Test08 {
	
//Attributes
public int x;


    
//Constructor
public Test08() { 	
}
	
	
//Compute
public void compute() {
    this.x = 5 * 4;
}


}