//Generated by dasze18
package math_expression;

import java.util.*;

public class Test02 {
	
//Attributes
public int x;


    
//Constructor
public Test02() { 	
}
	
	
//Compute
public void compute() {
    this.x = 40 + 2;
}


}