//Generated by dasze18
package math_expression;

import java.util.*;

public class Test05 {
	
//Attributes
public int x;


    
//Constructor
public Test05() { 	
}
	
	
//Compute
public void compute() {
    this.x = 4 - 46;
}


}