//Generated by dasze18
package math_expression;

import java.util.*;

public class Test10 {
	
//Attributes
public int x;


    
//Constructor
public Test10() { 	
}
	
	
//Compute
public void compute() {
    this.x = 20 / 4;
}


}