//Generated by dasze18
package math_expression;

import java.util.*;

public class Test09 {
	
//Attributes
public int x;


    
//Constructor
public Test09() { 	
}
	
	
//Compute
public void compute() {
    this.x = 5 * 4 * 6;
}


}