//Generated by dasze18
package math_expression;

import java.util.*;

public class Test06 {
	
//Attributes
public int x;


    
//Constructor
public Test06() { 	
}
	
	
//Compute
public void compute() {
    this.x = 42 - 4 - 80;
}


}