//Generated by dasze18
package math_expression;

import java.util.*;

public class Test15 {
	
//Attributes
public int x;


    
//Constructor
public Test15() { 	
}
	
	
//Compute
public void compute() {
    this.x = (10 + 3) * 7 - 4;
}


}