//Generated by dasze18
package math_expression;

import java.util.*;

public class Test17 {
	
//Attributes
public int x;


    
//Constructor
public Test17() { 	
}
	
	
//Compute
public void compute() {
    this.x = 42;
}


}