//Generated by dasze18
package math_expression;

import java.util.*;

public class Test33 {
	
//Attributes
public int a;
public int b;
public int c;
public int d;


    
//Constructor
public Test33() { 	
}
	
	
//Compute
public void compute() {
    this.a = 40;
    this.b = 2;
    this.c = b * 3;
    this.d = 4;
}


}