//Generated by dasze18
package math_expression;

import java.util.*;

public class Test11 {
	
//Attributes
public int x;


    
//Constructor
public Test11() { 	
}
	
	
//Compute
public void compute() {
    this.x = 4 / 20;
}


}