//Generated by dasze18
package math_expression;

import java.util.*;

public class Test12 {
	
//Attributes
public int x;


    
//Constructor
public Test12() { 	
}
	
	
//Compute
public void compute() {
    this.x = 120 / 6 / 5;
}


}