//Generated by dasze18
package math_expression;

import java.util.*;

public class Test19 {
	
//Attributes
public int x;


    
//Constructor
public Test19() { 	
}
	
	
//Compute
public void compute() {
    this.x = 2 + 79;
}


}