//Generated by dasze18
package math_expression;

import java.util.*;

public class Test07 {
	
//Attributes
public int x;


    
//Constructor
public Test07() { 	
}
	
	
//Compute
public void compute() {
    this.x = 100 - 20 + 10 - 3;
}


}