//Generated by dasze18
package math_expression;

import java.util.*;

public class Test23 {
	
//Attributes
public int x;
public int y;


    
//Constructor
public Test23() { 	
}
	
	
//Compute
public void compute() {
    this.x = 21;
    this.y = 2;
}


}