//Generated by dasze18
package math_expression;

import java.util.*;

public class Test26 {
	
//Attributes
public int x;
public int y;


    
//Constructor
public Test26() { 	
}
	
	
//Compute
public void compute() {
    this.x = 21;
    this.y = x + 1;
}


}