//Generated by dasze18
package math_expression;

import java.util.*;

public class Test18 {
	
//Attributes
public int x;


    
//Constructor
public Test18() { 	
}
	
	
//Compute
public void compute() {
    this.x = 10 * 8;
}


}