//Generated by dasze18
package math_expression;

import java.util.*;

public class Test25 {
	
//Attributes
public int x;
public int y;


    
//Constructor
public Test25() { 	
}
	
	
//Compute
public void compute() {
    this.x = 20;
    this.y = 21;
}


}