//Generated by dasze18
package math_expression;

import java.util.*;

public class Test21 {
	
//Attributes
public int x;
public int y;


    
//Constructor
public Test21() { 	
}
	
	
//Compute
public void compute() {
    this.x = 42;
    this.y = x;
}


}