//Generated by dasze18
package math_expression;

import java.util.*;

public class Test04 {
	
//Attributes
public int x;


    
//Constructor
public Test04() { 	
}
	
	
//Compute
public void compute() {
    this.x = 46 - 4;
}


}