//Generated by dasze18
package math_expression;

import java.util.*;

public class Test22 {
	
//Attributes
public int x;
public int y;


    
//Constructor
public Test22() { 	
}
	
	
//Compute
public void compute() {
    this.x = 40 + 2;
    this.y = x * 2;
}


}