//Generated by dasze18
package math_expression;

import java.util.*;

public class Test16 {
	
//Attributes
public int x;


    
//Constructor
public Test16() { 	
}
	
	
//Compute
public void compute() {
    this.x = 10 + 3 * 4 - 12 / 3 + 3;
}


}