//Generated by dasze18
package math_expression;

import java.util.*;

public class Test03 {
	
//Attributes
public int x;


    
//Constructor
public Test03() { 	
}
	
	
//Compute
public void compute() {
    this.x = 22 + 18 + 2;
}


}